# Generated by Django 4.1 on 2025-12-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(
                        db_column="ISBN",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_column="Title", max_length=100)),
                (
                    "publisher",
                    models.CharField(
                        blank=True, db_column="Publisher", max_length=100, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, db_column="Keywords", max_length=200, null=True
                    ),
                ),
                (
                    "coverimage",
                    models.TextField(blank=True, db_column="CoverImage", null=True),
                ),
                ("stockqty", models.IntegerField(db_column="StockQty")),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=50, null=True
                    ),
                ),
                ("minstocklimit", models.IntegerField(db_column="MinStockLimit")),
            ],
            options={
                "db_table": "book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookauthor",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("authorname", models.CharField(db_column="AuthorName", max_length=50)),
                ("authororder", models.IntegerField(db_column="AuthorOrder")),
            ],
            options={
                "db_table": "bookauthor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Creditlevel",
            fields=[
                (
                    "levelid",
                    models.IntegerField(
                        db_column="LevelID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "discountrate",
                    models.DecimalField(
                        db_column="DiscountRate", decimal_places=2, max_digits=3
                    ),
                ),
                ("canoverdraft", models.IntegerField(db_column="CanOverdraft")),
                (
                    "overdraftlimit",
                    models.DecimalField(
                        db_column="OverdraftLimit", decimal_places=2, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "creditlevel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customerid",
                    models.AutoField(
                        db_column="CustomerID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(db_column="Username", max_length=50, unique=True),
                ),
                ("password", models.CharField(db_column="Password", max_length=50)),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=200, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_column="Email",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_column="Balance", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "overdraftlimit",
                    models.DecimalField(
                        db_column="OverdraftLimit", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "totalspent",
                    models.DecimalField(
                        db_column="TotalSpent", decimal_places=2, max_digits=12
                    ),
                ),
                ("registerdate", models.DateTimeField(db_column="RegisterDate")),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orderdetail",
            fields=[
                (
                    "detailid",
                    models.AutoField(
                        db_column="DetailID", primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.IntegerField(db_column="Quantity")),
                (
                    "unitprice",
                    models.DecimalField(
                        db_column="UnitPrice", decimal_places=2, max_digits=10
                    ),
                ),
                ("isshipped", models.IntegerField(db_column="IsShipped")),
            ],
            options={
                "db_table": "orderdetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "orderid",
                    models.AutoField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "orderno",
                    models.CharField(db_column="OrderNo", max_length=30, unique=True),
                ),
                ("orderdate", models.DateTimeField(db_column="OrderDate")),
                (
                    "shipaddress",
                    models.CharField(db_column="ShipAddress", max_length=200),
                ),
                (
                    "totalamount",
                    models.DecimalField(
                        blank=True,
                        db_column="TotalAmount",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("status", models.IntegerField(db_column="Status")),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Procurement",
            fields=[
                (
                    "procid",
                    models.AutoField(
                        db_column="ProcID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "procno",
                    models.CharField(db_column="ProcNo", max_length=30, unique=True),
                ),
                ("createdate", models.DateTimeField(db_column="CreateDate")),
                ("status", models.IntegerField(db_column="Status")),
            ],
            options={
                "db_table": "procurement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Procurementdetail",
            fields=[
                (
                    "detailid",
                    models.AutoField(
                        db_column="DetailID", primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.IntegerField(db_column="Quantity")),
                (
                    "supplyprice",
                    models.DecimalField(
                        db_column="SupplyPrice", decimal_places=2, max_digits=10
                    ),
                ),
                ("receivedqty", models.IntegerField(db_column="ReceivedQty")),
            ],
            options={
                "db_table": "procurementdetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Shortagerecord",
            fields=[
                (
                    "recordid",
                    models.AutoField(
                        db_column="RecordID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "recordno",
                    models.CharField(db_column="RecordNo", max_length=30, unique=True),
                ),
                ("quantity", models.IntegerField(db_column="Quantity")),
                ("regdate", models.DateTimeField(db_column="RegDate")),
                ("sourcetype", models.IntegerField(db_column="SourceType")),
                ("status", models.IntegerField(db_column="Status")),
            ],
            options={
                "db_table": "shortagerecord",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "supplierid",
                    models.AutoField(
                        db_column="SupplierID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "suppliercode",
                    models.CharField(
                        db_column="SupplierCode", max_length=20, unique=True
                    ),
                ),
                (
                    "suppliername",
                    models.CharField(db_column="SupplierName", max_length=100),
                ),
                (
                    "supplylocation",
                    models.CharField(db_column="SupplyLocation", max_length=100),
                ),
                (
                    "contactinfo",
                    models.CharField(
                        blank=True, db_column="ContactInfo", max_length=200, null=True
                    ),
                ),
                ("isactive", models.IntegerField(db_column="IsActive")),
            ],
            options={
                "db_table": "supplier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplierbook",
            fields=[
                (
                    "supplierid",
                    models.OneToOneField(
                        db_column="SupplierID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="bookstore.supplier",
                    ),
                ),
                (
                    "supplyprice",
                    models.DecimalField(
                        blank=True,
                        db_column="SupplyPrice",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "lastsupplydate",
                    models.DateTimeField(
                        blank=True, db_column="LastSupplyDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "supplierbook",
                "managed": False,
            },
        ),
    ]
