# Generated by Django 6.0 on 2026-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0008_cart_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFavorite",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "verbose_name": "图书收藏",
                "verbose_name_plural": "图书收藏",
                "db_table": "book_favorite",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "browse_time",
                    models.DateTimeField(auto_now_add=True, db_column="browse_time"),
                ),
            ],
            options={
                "verbose_name": "浏览记录",
                "verbose_name_plural": "浏览记录",
                "db_table": "browse_history",
                "ordering": ["-browse_time"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FavoriteFolder",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="name", max_length=60)),
                ("is_default", models.IntegerField(db_column="is_default", default=0)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "verbose_name": "收藏夹",
                "verbose_name_plural": "收藏夹",
                "db_table": "favorite_folder",
                "ordering": ["-is_default", "created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("keyword", models.CharField(db_column="keyword", max_length=100)),
                (
                    "search_time",
                    models.DateTimeField(auto_now_add=True, db_column="search_time"),
                ),
            ],
            options={
                "verbose_name": "搜索记录",
                "verbose_name_plural": "搜索记录",
                "db_table": "search_history",
                "ordering": ["-search_time"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "managed": False,
                "verbose_name": "图书",
                "verbose_name_plural": "图书",
            },
        ),
        migrations.AlterModelOptions(
            name="bookauthor",
            options={
                "managed": False,
                "verbose_name": "图书作者",
                "verbose_name_plural": "图书作者",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "managed": True,
                "verbose_name": "购物车项",
                "verbose_name_plural": "购物车项",
            },
        ),
        migrations.AlterModelOptions(
            name="creditlevel",
            options={
                "managed": False,
                "verbose_name": "会员等级",
                "verbose_name_plural": "会员等级",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "managed": False,
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
            },
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "managed": True,
                "verbose_name": "会员档案",
                "verbose_name_plural": "会员档案",
            },
        ),
        migrations.AlterModelOptions(
            name="orderdetail",
            options={
                "managed": False,
                "verbose_name": "订单明细",
                "verbose_name_plural": "订单明细",
            },
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={
                "managed": False,
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.AlterModelOptions(
            name="procurement",
            options={
                "managed": False,
                "verbose_name": "采购单",
                "verbose_name_plural": "采购单",
            },
        ),
        migrations.AlterModelOptions(
            name="procurementdetail",
            options={
                "managed": False,
                "verbose_name": "采购明细",
                "verbose_name_plural": "采购明细",
            },
        ),
        migrations.AlterModelOptions(
            name="shortagerecord",
            options={
                "managed": False,
                "verbose_name": "缺货记录",
                "verbose_name_plural": "缺货记录",
            },
        ),
        migrations.AlterModelOptions(
            name="stripepaymentrecord",
            options={
                "managed": True,
                "verbose_name": "Stripe 支付记录",
                "verbose_name_plural": "Stripe 支付记录",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "managed": False,
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierbook",
            options={
                "managed": False,
                "verbose_name": "供应商图书",
                "verbose_name_plural": "供应商图书",
            },
        ),
    ]
