# Generated by Django 6.0 on 2026-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0009_bookfavorite_browsehistory_favoritefolder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAuthToken",
            fields=[
                (
                    "token",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("customer_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "APP登录令牌",
                "verbose_name_plural": "APP登录令牌",
                "db_table": "customer_auth_token",
                "managed": True,
                "indexes": [
                    models.Index(fields=["customer_id"], name="auth_token_customer_idx")
                ],
            },
        ),
    ]
